AWSTemplateFormatVersion: "2010-09-09"
Description: "template description"

Resources:
  CodeBucket:
    Type: AWS::S3::Bucket

Outputs:
  BucketName:
    Value: !Ref CodeBucket
    Description: Name of the sample Amazon S3 bucket with the source code for lambda functions. 
    Export:
      Name: !Sub "${AWS::StackName}-CodeBucketName"