version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install unittest

  build:
    commands:
      - python -m unittest discover test

