AWSTemplateFormatVersion: '2010-09-09'
# *** Change this to something useful for you!
Description: template for creating pipelines

Parameters:
  BucketsStackName:
    Type: String
    Default: 'BucketsStack'
  RepoOwner:
    Type: String
    Default: 'hadaszm'
  RepoName:
    Type: String
    Default: 'test_repo'
  RepoBranch:
    Type: String
    Default: 'main'
  BucketsStackName:
    Type: String
    Default: 'BucketsStack'
  LambdasStackName:
    Type: String
    Default: 'LambdasStack'
  ApiGatewayStackName:
    Type: String
    Default: 'ApiGatewayStack'
  PipelineRole:
    Type: String
    Default:  arn:aws:iam::980494704750:role/LabRole
  OAuthToken:
    Type: String
    Default: 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

Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactsBucket
      RestartExecutionOnUpdate: true
      RoleArn: !Ref PipelineRole
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: 1
            Provider: GitHub
          OutputArtifacts:
          - Name: SourceCode
          Configuration:
            Owner: !Ref RepoOwner
            Repo: !Ref RepoName
            Branch: !Ref RepoBranch
            PollForSourceChanges: false
            OAuthToken: !Ref OAuthToken
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: Lambda1Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: S3
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            BucketName: "${BucketsStackName}-CodeBucketName"
            Extract: 'false'
            ObjectKey: SourceCode::zips/delete_celeb_lambda.zip
          Region: !Ref 'AWS::Region'
        - Name: Lambda2Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: S3
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            BucketName: "${BucketsStackName}-CodeBucketName"
            Extract: 'false'
            ObjectKey: SourceCode::zips/rekognition_lambda.zip
          Region: !Ref 'AWS::Region'          
        - Name: Lambda3Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: S3
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            BucketName: "${BucketsStackName}-CodeBucketName"
            Extract: 'false'
            ObjectKey: SourceCode::zips/save_results_lambda.zip
          Region: !Ref 'AWS::Region'
        - Name: Lambda4Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: S3
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            BucketName: "${BucketsStackName}-CodeBucketName"
            Extract: 'false'
            ObjectKey: SourceCode::zips/send_report_lambda.zip
          Region: !Ref 'AWS::Region'        
        - Name: Lambda5Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: S3
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            BucketName: "${BucketsStackName}-CodeBucketName"
            Extract: 'false'
            ObjectKey: SourceCode::zips/subscribe_reports_lambda.zip
          Region: !Ref 'AWS::Region'

  GithubWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref
      RegisterWithThirdParty: 'true'
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt CodePipeline.Version


