AWSTemplateFormatVersion: '2010-09-09'
# *** Change this to something useful for you!
Description: template for creating pipelines

Parameters:
  BucketsStackName:
    Type: String
    Default: 'BucketsStack'
  RepoOwner:
    Type: String
    Default: hadaszm
  RepoName:
    Type: String
    Default: 'test_repo' 
  RepoBranch:
    Type: String
    Default: 'main'
  PipelineRole:
    Type: String
    Default: arn:aws:iam::980494704750:role/LabRole
  OAuthToken:
    Type: String
    Default: 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

Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactsBucket
      RestartExecutionOnUpdate: true
      RoleArn: !Ref PipelineRole
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: 1
            Provider: GitHub
          OutputArtifacts:
          - Name: SourceArtifact
          Configuration:
            Owner: !Ref RepoOwner
            Repo: !Ref RepoName
            Branch: !Ref RepoBranch
            PollForSourceChanges: false
            OAuthToken: !Ref OAuthToken
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: Lambda1Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: S3
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            BucketName: 
              Fn::ImportValue:
                !Sub "${BucketsStackName}-CodeBucketName"
            Extract: 'true'
            ObjectKey: "repo" 
          Region: !Ref 'AWS::Region'
          OutputArtifacts: []
          RunOrder: 1   
      - Name: LambdaInvoke
        Actions:
        - Name: LambdaInvoke
          ActionTypeId:
            Category: Invoke
            Owner: AWS
            Provider: Lambda
            Version: '1'
          Configuration:
            FunctionName: SimpleLambda
          Region: !Ref 'AWS::Region'
          InputArtifacts: []
          OutputArtifacts: []
          RunOrder: 1   


  GithubWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref OAuthToken
      RegisterWithThirdParty: 'true'
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt CodePipeline.Version



